### ISSUE TITLE
Vapour Pressure 118/117

### ISSUE THREAD

**Issue by raakal** [open-archives-data-rescue/climate-data-rescue#374]
On some pages when users attempt to add the numeric value for Vapour Pressure, and it is 118/117, it changes the number to 'illegible'.

Users are  currently leaving these values 'empty' and making a Transcriber comment to highlight the issue as occurring alongside filling out the Google Issues Form.

Some examples:

https://citsci.geog.mcgill.ca/en/transcriptions/2692/edit
https://citsci.geog.mcgill.ca/en/transcriptions/2620/edit (4th 7:48pm, 10:48pm)
https://citsci.geog.mcgill.ca/en/transcriptions/2609 (29th 10:48pm)

**Comment by VickyS08** [comment]
We think this is because the field ID is 118, and similarly for other similar field with ID 117, etc. When users enter 117 ,118 and similar values, there is a conflict and the value defaults to "illegible"

Additional comments:
https://draw.geog.mcgill.ca//en/transcriptions/2692/edit: issue occurs when trying to edit Pressure of Vapour values on the 12th at 7:48pm, 10:48pm, and 11:13pm. When I edit the current value, which is Empty/Blank, and enter 117 instead, it defaults back to Empty/Blank. If I try to enter 118, instead, it will accept that value.
https://draw.geog.mcgill.ca//en/transcriptions/2620/edit: issue occurs when trying to edit Pressure of Vapour values on the 4th at 7:48pm and 10:48pm. When I edit the current value, which is Illegible, and enter 118 instead, it defaults back to Illegible. If I try to enter 117, instead, it will accept that value.
https://draw.geog.mcgill.ca//en/transcriptions/2609/edit: Rachel flagged this transcription as an example, but it allowed me to edit the Pressure of Vapour value on the 29th at 10:48pm from Empty/Blank to 117, which is the correct value.
Takeaway: this issue persists in some transcriptions, but not in others previously flagged as exhibiting the issue. I thought that the issue may be related to the register type, but all three examples are Register 110, page 1. Maybe the issue is connected to the field?

**Comment by VickyS08** [comment]
Tested and values appear as 117, 118 and 119 on the test site on 2023-02-28
